name: flutter_book_manager
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_mobx: ^2.0.6+5
  flutter_modular: ^5.0.3
  intl: ^0.17.0
  mobx: ^2.1.3

dev_dependencies:
  build_runner: any
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mobx_codegen: any
  modular_codegen: ^3.0.4

flutter:
  uses-material-design: true
